:last-update-label!:
:am-version: latest
:source-highlighter: rouge
:rouge-style: base16.monokai

ifdef::env-github[:am-base-path: ../../main]
ifndef::env-github[:am-base-path: ../..]
ifdef::env-github[:api-base: link:https://redboltz.github.io/async_mqtt/doc/{am-version}/html]
ifndef::env-github[:api-base: link:../api]

= Using stackless coroutine

This is stackless coroutine approach. It uses switch-case based Boost.Asio stackless corotuine.
See https://www.boost.org/doc/html/boost_asio/overview/composition/coroutine.html

It is convenient but a little tricky. Due to switch-case based, there are some restrictions especially define local variables.
If you can use xref:cpp20_coro.adoc[C++20 coroutine], I recommend use it.

stackless coroutine can avoid deeply nested callbacks. The code becomes easy to read.

== Prepare your application class

Here is a application class prototype:

```cpp
#include <boost/asio/yield.hpp>

template <typename Executor>
struct app {

private:
    struct impl {
        impl(app& a):app_{a}
        {
        }
        // forwarding callbacks
        void operator()() const {
            proc({}, {}, {});
        }
        void operator()(boost::system::error_code const& ec) const {
            proc(ec, {}, {});
        }
        void operator()(am::system_error const& se) const {
            proc({}, se, {});
        }
        void operator()(am::packet_variant pv) const {
            proc({}, {}, am::force_move(pv));
        }
    private:
        void proc(
            boost::system::error_code const& ec,
            am::system_error const& se,
            am::packet_variant pv
        ) const {

            reenter (coro_) {
                std::cout << "start" << std::endl;
            }
        }

    private:
        app& app_;
        mutable as::coroutine coro_;
    };

    impl impl_{*this};
};
#include <boost/asio/unyield.hpp>
```

Then, add the app's constructor as follows. endpoint is created here. In the body of the constructor, `impl_()` is called. Then the coroutine is started.
Then,Declare the app's member variables.

```cpp
    app(Executor exe,
        std::string_view host,
        std::string_view port
    ):host_{std::move(host)},
      port_{std::move(port)},
      amep_{am::endpoint<am::role::client, am::protocol::mqtt>::create(am::protocol_version::v3_1_1, exe)}
    {
        impl_();
    }
    // ...

private:
    void proc(
        boost::system::error_code const& ec,
        am::system_error const& se,
        am::packet_variant pv
    ) {
        reenter (coro) {
        }
    }

    std::string_view host_;
    std::string_view port_;
    std::shared_ptr<am::endpoint<am::role::client, am::protocol::mqtt>> amep_;
    std::size_t count_ = 0;
    impl impl_{*this};
    // prepare will message if you need.
    am::will will{
        "WillTopic1",
        "WillMessage1",
        am::qos::at_most_once,
        { // properties
            am::property::user_property{"key1", "val1"},
            am::property::content_type{"text"},
        }
    };
};
```

Then, implement `int main()` as follows:

```cpp
int main(int argc, char* argv[]) {
    if (argc != 3) {
        std::cout << "Usage: " << argv[0] << " host port" << std::endl;
        return -1;
    }
    am::setup_log(am::severity_level::trace);
    as::io_context ioc;
    app a{ioc.get_executor(), argv[1], argv[2]};
    ioc.run();
}
```

When you execute the program, you can see `start` output message. This indicates that the coroutine is started well.

```cpp
        void proc(
            boost::system::error_code const& ec,
            am::system_error const& se,
            am::packet_variant pv
        ) const {

            reenter (coro_) {
                std::cout << "start" << std::endl;
```

This is the basic of stackless coroutine approach.
Now, adding more meaningful sequence.

== Handshake underlying layers (mqtt, mqtts, ws, wss)

```cpp
        void proc(
            boost::system::error_code const& ec,
            am::system_error const& se,
            am::packet_variant pv
        ) const {

            reenter (coro_) {
                std::cout << "start" << std::endl;

                // Handshake undlerying layer (Name resolution and TCP handshaking)
                yield am::underlying_handshake(
                    app_.amep_->next_layer(),
                    app_.host_,
                    app_.port_,
                    *this
                );

                std::cout
                    << "Underlying layer connected ec:"
                    << ec.message()
                    << std::endl;

                if (ec) return;
```

The important point is

```cpp
                yield am::underlying_handshake(
                    app_.amep_->next_layer(),
                    app_.host_,
                    app_.port_,
                    *this
                );
```

The fourth argument of underlying_handshake is CompletionToken. When we use stackless coroutine, we pass `*this` as the CompletionToken. The function proc() is implicitly returned and underlying_handshake starts processing.
When async process is finished, then the following operator() is called:

```cpp
        void operator()(boost::system::error_code const& ec) const {
            proc(ec, {}, {});
        }
```

Then, proc is called. You can distinguish which async process is finished by proc()'s parameter.
You can check `ec` as follows:

```cpp
                std::cout
                    << "Underlying layer connected ec:"
                    << ec.message()
                    << std::endl;

                if (ec) return;
```

Even if proc() is called again, the following part of the code is skipped:

```cpp
                std::cout << "start" << std::endl;

                // Handshake undlerying layer (Name resolution and TCP handshaking)
                yield am::underlying_handshake(
                    app_.amep_->next_layer(),
                    app_.host_,
                    app_.port_,
                    *this
                );
```

This is switch-case based Boost.Asio stackless coroutine mechanism.
See https://www.boost.org/doc/html/boost_asio/overview/composition/coroutine.html

== Send MQTT CONNECT packet

Create MQTT CONNECT packet and send it as follows:

```cpp
                // Send MQTT CONNECT
                yield app_.amep_->send(
                    am::v3_1_1::connect_packet{
                        true,   // clean_session
                        0x1234, // keep_alive
                        "ClientIdentifier1",
                        app_.will,   // you can pass std::nullopt if you don't want to set the will message
                        "UserName1",
                        "Password1"
                    },
                    *this
                );
```

When async process is finished the function resumes at the following line:

```cpp
                if (se) {
                    std::cout << "MQTT CONNECT send error:" << se.what() << std::endl;
                    return;
                }
```

The parameter of the completion token is `system_error const& se`.
See {api-base}/++classasync__mqtt_1_1basic__endpoint.html++[API reference].

== Recv MQTT CONNACK packet

Receive MQTT packet as follows:

```cpp
                // Recv MQTT CONNACK
                yield app_.amep_->recv(*this);
```

When a packet is received then the function resumes at the following line:

```cpp
                if (pv) {
                    pv.visit(
                        am::overload {
                            [&](am::v3_1_1::connack_packet const& p) {
                                std::cout
                                    << "MQTT CONNACK recv"
                                    << " sp:" << p.session_present()
                                    << std::endl;
                            },
                            [](auto const&) {}
                        }
                    );
                }
                else {
                    std::cout
                        << "MQTT CONNACK recv error:"
                        << pv.get<am::system_error>().what()
                        << std::endl;
                    return;
                }
```

The parameter of the completion token is `packet_variant pv`. You can access the `pv` using visit function and overloaded lamnda expressions. Each lambda expression is corresponding to the actual packet type.
`pv` can be evalurated as bool. If any receive error happens then `pv` evaluated as false, otherwise true.

== Send/Recv packets
See the simple example xref:{am-base-path}/example/ep_slcoro_mqtt_client.cpp[ep_slcoro_mqtt_client.cpp].

If you want to know more complex usecase, xref:{am-base-path}/tool/client_cli.cpp[client_cli.cpp] is helpful.
This is commandline MQTT client application.

== Examples
* xref:{am-base-path}/example/ep_slcoro_mqtt_client.cpp[ep_slcoro_mqtt_client.cpp]
* xref:{am-base-path}/example/ep_slcoro_mqtts_client.cpp[ep_slcoro_mqtts_client.cpp]
* xref:{am-base-path}/example/ep_slcoro_ws_client.cpp[ep_slcoro_ws_client.cpp]
* xref:{am-base-path}/example/ep_slcoro_wss_client.cpp[ep_slcoro_wss_client.cpp]
