:am-version: latest
:source-highlighter: rouge
:rouge-style: base16.monokai

ifdef::env-github[:am-base-path: ../main]
ifndef::env-github[:am-base-path: ..]
ifdef::env-github[:api-base: link:https://redboltz.github.io/async_mqtt/doc/{am-version}/html]
ifndef::env-github[:api-base: link:api]

= Coding Rule

== Conditional branch

* If the branch has `else` clause, corresponding `if` should be used with **positive** condition.

* Good example:

```cpp
#if defined(ASYNC_MQTT_VAL1)
    // do some on defined
#else  // defined(ASYNC_MQTT_VAL1)
    // do some on not defined
#endif // defined(ASYNC_MQTT_VAL1)

if (val1 == 10) {
    // do some on val1 == 10
}
else {
    // do some on val1 != 10
}
```

* Bad example

```cpp
#if !defined(ASYNC_MQTT_VAL1)
    // do some on not defined
#else  // !defined(ASYNC_MQTT_VAL1)
    // do some on defined
#endif // !defined(ASYNC_MQTT_VAL1)

if (val1 != 10) {
    // do some on val1 != 10
}
else {
    // do some on val1 == 10
}
```

== Include guard

For file `include/async_mqtt/file.hpp`
```cpp
#if !defined(ASYNC_MQTT_FILE_HPP)
#define ASYNC_MQTT_FILE_HPP

#endif // ASYNC_MQTT_FILE_HPP
```

For file `include/async_mqtt/sub1/file.hpp`
```cpp
#if !defined(ASYNC_MQTT_SUB1_FILE_HPP)
#define ASYNC_MQTT_SUB1_FILE_HPP

#endif // ASYNC_MQTT_SUB1_FILE_HPP
```

* Use `#if !defined()`
* Add comment after `#endif`. It doesn't contain `!defined()`.
** It is a special rule for include guard.

== Macro

=== Values

* The name of the values must be start with `ASYNC_MQTT_`.

=== Conditional branch

* Don't use `#ifdef` and `#ifndef`, use `#if defined(...)`.
* Add comment after `#else  ` and `#endif`. For `#else` adiitional one whitespace is required. The contents of the comment should be the same as `#if` condition.
* Good example:
```cpp
#if defined(ASYNC_MQTT_VAL1)
#else  // defined(ASYNC_MQTT_VAL1)
#endif // defined(ASYNC_MQTT_VAL1)
```

== namespace

* `namespace` doesn't introduce indent.
* After the comment end of the namespace `}` , the contnents of the comment is `namespace ns`.
* Good example:
```cpp
namespace async_mqtt {
// ...
namespace detail {

struct foo;

} // namespace detail

} // namespace async_mqtt
```

== Whiltespace and Line break

* Whilespace rule is here:

```cpp
if (val == 1) {
}
else if (val == 2) {
}
else {
}
```

```cpp
for (int i = 0; i != 10; ++i) {
}
```

```cpp
for (auto const& p : props) {
}
```

```cpp
while (i != 10) {
}
```

```cpp
do {
    // ....
} while (true);
```

```cpp
switch (val) {
case 1:
    ++val;
    break;
case 2: {
    int j = val;
    ++val;
} break;
default:
    break;
}
```

```cpp
auto lambda =
    [val1, val2](int param) -> ret_type {
    };

lambda(1);
```

* immediate invoke case.
** use `&` is allowed.
```cpp
auto lambda =
    [&] {
    } ();

lambda(1);
```

* long capture list, or long parameter case:
```cpp
auto lambda =
    [
        val1 = std::move(val1),
        val2,
        val3,
        val4,
        val5,
        val6
    ]
    (
        int param1,
        int param2,
        int param3,
        int param4,
        int param5
    ) -> ret_type {
    };
```

```cpp
template <typename T, typename U>
void func(T t, U u) {
}
```

* long parameters case
```cpp
template <
    typename T1,
    typename T2,
    typename T3,
    typename T4,
    typename T5,
    typename T6,
    typename T7
>
void func(
    T1 t1,
    T2 t2,
    T3 t3,
    T4 t4,
    T5 t5,
    T6 t6,
    T7 t7
) {
}
```

* SFINAE case. Adjust `>` position like as follows:
```cpp
template <typname T>
std::enable_if_t<
    std::is_same_v<
        std::decay_t<T>,
        int
    >
>
foo(T t) {
}
```
