:last-update-label!:
:am-version: latest
:source-highlighter: rouge
:rouge-style: base16.monokai

ifdef::env-github[:am-base-path: ../main]
ifndef::env-github[:am-base-path: ..]
ifdef::env-github[:api-base: link:https://redboltz.github.io/async_mqtt/doc/{am-version}/html]
ifndef::env-github[:api-base: link:api]

= Simple Pub/Sub client

== Get async_mqtt and build examples

```sh
git clone https://github.com/redboltz/async_mqtt.git
cd async_mqtt
cmake  -DASYNC_MQTT_USE_LOG=ON -DASYNC_MQTT_BUILD_EXAMPLES=ON ..
```

=== C++20 coroutine version

```
make cl_cpp20coro_mqtt_pub
make cl_cpp20coro_mqtt_sub
cd example
```

==== Run subscriber

```sh
./cl_cpp20coro_mqtt_sub mqtt.redboltz.net 1883
```

* xref:{am-base-path}/example/cl_cpp20coro_mqtt_sub.cpp[Simple subscribe client]

==== Run publisher

At another terminal, run publisher.

```sh
./cl_cpp20coro_mqtt_pub mqtt.redboltz.net 1883
```

Then, you can see the published messages to delivered to the subscriber.

* xref:{am-base-path}/example/cl_cpp20coro_mqtt_pub.cpp[Simple publish client]


=== C++17 callback version

```
make cl_cpp17_mqtt_pub
make cl_cpp17_mqtt_sub
cd example
```

==== Run subscriber

```sh
./cl_cpp17_mqtt_sub mqtt.redboltz.net 1883
```

* xref:{am-base-path}/example/cl_cpp17_mqtt_sub.cpp[Simple subscribe client]

==== Run publisher

At another terminal, run publisher.

```sh
./cl_cpp17_mqtt_pub mqtt.redboltz.net 1883
```

Then, you can see the published messages to delivered to the subscriber.

* xref:{am-base-path}/example/cl_cpp17_mqtt_pub.cpp[Simple publish client]
