= Free trial broker on cloud

You can connect to the broker `async-mqtt.redboltz.net` for testing.

|===
|port|protocol|client_cli.sh access

|1883|MQTT on TCP|./client_cli.sh --host async-mqtt.redboltz.net --port 1883 --protocol mqtt
|8883|MQTT on TLS(verify_peer)|./client_cli.sh --host async-mqtt.redboltz.net --port 8883 --protocol mqtts
|80|MQTT on Websocket|./client_cli.sh --host async-mqtt.redboltz.net --port 80 --protocol ws
|443|MQTT on Websocket(TLS, verify_none)|./client_cli.sh --host async-mqtt.redboltz.net --port 443 --protocol wss
|10443|MQTT on Websocket(TLS, verify_peer)|./client_cli.sh --host async-mqtt.redboltz.net --port 10443 --protocol wss
|===

* verify_peer: If a client prepare to send Client Certificate, the broker verify it.
* verify_none: Even if a client prepare to send Client Certificate, the client doesn't send it during TLS handshaking.
** If a browser find Client Certificates, direct accessing to wss:// would error. See https://github.com/redboltz/async_mqtt/pull/433 This setting can avoid the error.

* verify_peer: If a client is prepared to send a client certificate, the broker will verify it.
* verify_none: Even if a client is prepared to send a client certificate, it will not be sent during the TLS handshake.
  * If a browser detects available client certificates, directly accessing. See https://github.com/redboltz/async_mqtt/pull/433 . This setting prevents that error.

== Important notice

You are free to use it for any application, but please do not abuse or rely upon it for anything of importance. This server runs on an very low spec vps. It is not intended to demonstrate any performance characteristics.
Please don't publish anything sensitive, anybody could be listening.
