:last-update-label!:
:am-version: latest
:source-highlighter: rouge
:rouge-style: base16.monokai

ifdef::env-github[:am-base-path: ../../main]
ifndef::env-github[:am-base-path: ../..]
ifdef::env-github[:api-base: link:https://redboltz.github.io/async_mqtt/doc/{am-version}/html]
ifndef::env-github[:api-base: link:../api]

= Maximum Packet Size


The Maximum Packet Size is a way to control the size of all packets. If a node sends a packet larger than the Maximum Packet Size, it is considered a protocol error. The counterpart disconnects the connection with a DISCONNECT packet with Reason Code 0x95 (Packet too large).

== Notifying Maximum Packet Size


There are two independent Maximum Packet Size limits.

[mermaid]
ifdef::env-github[[source,mermaid]]
....
sequenceDiagram
client1->>broker: CONNECT MaximumPacketSize=10000
Note right of broker: broker can send at most 10000 bytes packet to client1
broker->>client1: CONNACK ReceiveMaximum=20000
Note left of client1: client1 can send at most 20000  bytes packet to the broker
....
