:last-update-label!:
:am-version: latest
:source-highlighter: rouge
:rouge-style: base16.monokai

ifdef::env-github[:am-base-path: ../../main]
ifndef::env-github[:am-base-path: ../..]
ifdef::env-github[:api-base: link:https://redboltz.github.io/async_mqtt/doc/{am-version}/html]
ifndef::env-github[:api-base: link:../api]

= Request/Response

MQTT's communication model is a pub/sub model. In order to realize Request/Response on the pub/sub model, MQTT v5.0 uses the following mechanism.

[mermaid]
ifdef::env-github[[source,mermaid]]
....
sequenceDiagram
client1->>broker: CONNECT RequestResponseInformation=1
Note right of broker: BGTFC1 means Broker Generated Topic For Client1
broker->>client1: CONNACK ResponseInformation=BGTFC1
client1->>broker: SUBSCRIBE BGTFC1
broker->>client1: SUBACK
client2->>broker: SUBSCRIBE TopicFilter=ControlTopic
broker->>client2: SUBACK
client1->>broker: PUBLISH TopicName=ControlTopic, ResponseTopic=BGTFC1, Payload=TurnOnSwitch
broker->>client2: deliver PUBLISH
Note left of client2: Use BGTFC1 for response
client2->>broker: PUBLISH TopicName=BGTFC1 Payload=TurnOnSuccess
broker->>client1: deliver PUBLISH
Note right of client1: Got the control response
....

== Client

async_mqtt doesn't perform any special treatment for Request/Response. Simply send a CONNECT packet with the `RequestResponseInformation` property set to 1, and then receive the CONNACK packet. If the CONNACK packet includes `ResponseInformation`, you can obtain `ResponseInformation` from it and subscribe to it.

== Broker

The broker part of async_mqtt supports Request/Response. When the broker receives a CONNECT packet with `RequestResponseInformation` set to 1, it automatically generates `ResponseInformation` and sends back a CONNACK packet with it. `ResponseInformation` is the `TopicName` for the response, so the client can use it as the `ResponseTopic` property when sending a PUBLISH packet.
The async_mqtt broker has authentication/authorization support. The generated topic can be subscribed to only by the client that sent `RequestResponseInformation`. The generated topic can be published to by all clients.

== Correlation Data

See https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901115

The client has only one `ResponseTopic` and uses it for all requests. The request receiver client could be different, so the responses could be mixed. To distinguish the correct response, `CorrelationData` can be used. See the following diagram.


[mermaid]
ifdef::env-github[[source,mermaid]]
....
sequenceDiagram
Note right of client1: omit broker
client1->>client2: PUBLISH TopicName=T2, ResponseTopic=R1, CorrelationData=UnpredictableString2, Payload=ON
client1->>client3: PUBLISH TopicName=T3, ResponseTopic=R1, CorrelationData=UnpredictableString3, Payload=ON
client2->>client1: PUBLISH TopicName=R1, CorrelationData=UnpredictableString2, Payload=Failed
client3->>client1: PUBLISH TopicName=R1, CorrelationData=UnpredictableString3, Payload=Success
....

client1 got the ResponseInformation R1 and uses it as ResponseTopic. Both client2 and client3 receive the same ResponseTopic and use it for publish back the response.
If control PUBLISH packet contains not only ResponseTopic but also CorrelationData, then the receiver just set the CorrelationData to the response PUBLISH packet.

client1 can choose any string as CorrelationData. Typically, choose unpredictable string to avoid malformed response.
client1 needs to manage a CorrelationData-Request map to check the corresponding request.
